steps:
  - id: 'Get Cluster Credentials'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud config set project $PROJECT_ID
        gcloud container clusters get-credentials autopilot-cluster-1 --region us-east1 --project allfitness-production

  - id: 'Install Gateway-api'
    name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'k8s-resources/v2/project-dev/cluster-gke-dev/gateway-api.yml'
    env:
      - 'KUBECONFIG=/root/.kube/config'
      - "CLOUDSDK_COMPUTE_REGION=${_CLUSTER_ZONE}"
      - "CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}"

  - id: 'Install Nginx Gateway Fabric'
    name: 'alpine/helm:3.15.4'
    args:
     - '-c'
      - |
        apk add --no-cache curl bash openssl python3 py3-crcmod
        curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-367.0.0-linux-x86_64.tar.gz
        tar -xf google-cloud-sdk-367.0.0-linux-x86_64.tar.gz
        ./google-cloud-sdk/install.sh --quiet
        export PATH=$PATH:/google-cloud-sdk/bin
        gcloud components install gke-gcloud-auth-plugin --quiet
        export USE_GKE_GCLOUD_AUTH_PLUGIN=True
        helm install ngf .
    dir: 'k8s-resources/v2/project-dev/cluster-gke-dev/nginx-gateway-fabric'
    env:
      - "CLOUDSDK_COMPUTE_REGION=${_CLUSTER_ZONE}"
      - "CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}"

  - id: 'Install Gateway'
    name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'k8s-resources/v2/project-dev/cluster-gke-dev/gateway.yaml'
    env:
      - "CLOUDSDK_COMPUTE_REGION=${_CLUSTER_ZONE}"
      - "CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}"

  - id: 'Get Deployment Status'
    name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'rollout'
      - 'status'
      - 'deployment/${_DEPLOYMENT_NAME}'
      - '--namespace'
      - '${_K8S_NAMESPACE}'
      - '--timeout=600s'
    env:
      - "CLOUDSDK_COMPUTE_REGION=${_CLUSTER_ZONE}"
      - "CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}"
substitutions:
  _CLUSTER_NAME: 'autopilot-cluster-1'
  _CLUSTER_ZONE: 'us-east1'
  _K8S_NAMESPACE: 'default'
  _DEPLOYMENT_NAME: 'ngf-nginx-gateway-fabric'
options:
  logging: CLOUD_LOGGING_ONLY
