steps:
  - id: 'Get Cluster Credentials'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud config set project $PROJECT_ID
        gcloud container clusters get-credentials autopilot-cluster-1 --region us-east1 --project allfitness-production

  - id: 'Install Gateway-api'
    name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'k8s-resources/v2/project-dev/cluster-gke-dev/gateway-api.yml'
    env:
      - 'KUBECONFIG=/root/.kube/config'
      - "CLOUDSDK_COMPUTE_REGION=${_CLUSTER_ZONE}"
      - "CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}"

  - id: 'Install Nginx Gateway Fabric'
    name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        helm install ngf .
    dir: 'k8s-resources/v2/project-dev/cluster-gke-dev/nginx-gateway-fabric'
    env:
      - "CLOUDSDK_COMPUTE_REGION=${_CLUSTER_ZONE}"
      - "CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}"

  - id: 'Install Gateway'
    name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'k8s-resources/v2/project-dev/cluster-gke-dev/gateway.yaml'
    env:
      - "CLOUDSDK_COMPUTE_REGION=${_CLUSTER_ZONE}"
      - "CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}"

  - id: 'Get Deployment Status'
    name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'rollout'
      - 'status'
      - 'deployment/${_DEPLOYMENT_NAME}'
      - '--namespace'
      - '${_K8S_NAMESPACE}'
      - '--timeout=600s'
    env:
      - "CLOUDSDK_COMPUTE_REGION=${_CLUSTER_ZONE}"
      - "CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}"
substitutions:
  _CLUSTER_NAME: 'autopilot-cluster-1'
  _CLUSTER_ZONE: 'us-east1'
  _K8S_NAMESPACE: 'default'
  _DEPLOYMENT_NAME: 'ngf-nginx-gateway-fabric'
options:
  logging: CLOUD_LOGGING_ONLY
